apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: dream-aesthetics-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: stefanknez/ai-service:latest
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: dream-aesthetics-ns
spec:
  selector:
    app: ai-service
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP