apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service-local
  namespace: dream-aesthetics-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service-local
  template:
    metadata:
      labels:
        app: ai-service-local
    spec:
      containers:
        - name: ai-service
          image: ai-service-local:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service-local
  namespace: dream-aesthetics-ns
spec:
  selector:
    app: ai-service-local
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP