apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-local
  namespace: dream-aesthetics-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-local
  template:
    metadata:
      labels:
        app: frontend-local
    spec:
      containers:
        - name: frontend
          image: dream-frontend-local:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-local
  namespace: dream-aesthetics-ns
spec:
  selector:
    app: frontend-local
  type: LoadBalancer
  ports:
    - port: 5173      
      targetPort: 5173 